require('dotenv').config();
const express=require('express');
const cors=require('cors');
const connectDB=require('./config/db');
connectDB();
const app=express();
app.use(cors());
app.use(express.json());
app.use('/api/auth',require('./routes/authRoutes'));
app.use('/api/workouts',require('./routes/workoutRoutes'));
app.use('/api/goals',require('./routes/goalRoutes'));
app.get('/',(req,res)=>res.send('FitPulse API Running'));
app.listen(process.env.PORT||5000,()=>console.log('Server Running'));
